theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
site_name: Homepage
site_url: https://do-thanh2201.github.io/
site_author: Đỗ Thành
site_description: Tài liệu tổng hợp của Đỗ Thành
nav:
  - Home: 'index.md'
  - 'Back-end':
    - 'Java':
      - Home: 'backend/Java/index.md'
    - 'Springboot and Micro Services':
      - Home: 'backend/Springboot and MicroServices/index.md'
  - 'Front-end':
    - 'CSS':
      - "Box Model": 'frontend/CSS/boxModel.md'
      - "Box Position": 'frontend/CSS/boxPosition.md'
      - "Fexbox": 'frontend/CSS/flexbox.md'
      - "Grid": 'frontend/CSS/grid.md'
      - "Others": 'frontend/CSS/others.md'
    - 'JavaScript':
      - Home: 'frontend/JavaScript/index.md'