theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - yaml
site_name: Homepage
site_url: https://do-thanh2201.github.io/
site_author: Đỗ Thành
site_description: Tài liệu tổng hợp của Đỗ Thành
nav:
  - Home: 'index.md'
  - 'Back-end':
    - 'Java':
      - Mở đầu: 'backend/Java/index.md'
    - 'Springboot and Micro Services':
      - Mở đầu: 'backend/Springboot and MicroServices/index.md'
  - 'Front-end':
    - 'CSS':
      - "Selectors": 'frontend/CSS/1 selectors.md'
      - "Cascading and Inheritance": 'frontend/CSS/2 Cascading and Inheritance.md'
      - "Box Model": 'frontend/CSS/3 boxModel.md'
      - "Box Position": 'frontend/CSS/4 boxPosition.md'
      - "FLow": 'frontend/CSS/5 flow.md'
      - "Flexbox": 'frontend/CSS/6 flexbox.md'
      - "Grid": 'frontend/CSS/7 grid.md'
      - "Others": 'frontend/CSS/others.md'
    - 'JavaScript':
      - Mở đầu: 'frontend/JavaScript/index.md'